# Generated by Django 5.0.2 on 2024-03-26 08:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_date_begin', models.DateField()),
                ('course_time_begin', models.TimeField(default='10:00')),
                ('course_location', models.CharField(default='127083, г. Москва, ул. Верхняя Масловка д. 20, стр. 2', max_length=100)),
                ('course_tutor', models.CharField(max_length=100)),
                ('course_date_end', models.DateField()),
                ('course_time_end', models.TimeField(default='17:00')),
                ('course_status', models.CharField(choices=[('Запланирован', 'Запланирован'), ('Подтвержден', 'Подтвержден'), ('Проведен', 'Проведен'), ('Отменен', 'Отменен')], default='Запланирован', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_last_name_rus', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')])),
                ('attendee_first_name_rus', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')])),
                ('attendee_fathers_name_rus', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')])),
                ('attendee_last_name_eng', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^([A-Z][-,a-z. ]+[ ]*)+$')])),
                ('attendee_first_name_eng', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^([A-Z][-,a-z. ]+[ ]*)+$')])),
                ('attendee_email', models.EmailField(max_length=100)),
                ('attendee_phone', models.CharField(max_length=20)),
                ('attendee_company', models.CharField(max_length=100)),
                ('attendee_position', models.CharField(max_length=50)),
                ('attendee_contract_number', models.CharField(max_length=25)),
                ('attendee_contract_status', models.CharField(choices=[('Не направлен', 'Не направлен'), ('Направлен', 'Направлен'), ('Подписан', 'Подписан')], default='Не направлен', verbose_name='Статус договора')),
                ('attendee_invoice_status', models.CharField(choices=[('Не оплачен', 'Не оплачен'), ('Оплачен', 'Оплачен'), ('Постоплата', 'Постоплата')], default='Не оплачен', verbose_name='Статус счета')),
                ('attendee_course_price', models.CharField(max_length=25)),
                ('attendee_contact_last_name_rus', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')])),
                ('attendee_contact_first_name_rus', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')])),
                ('attendee_contact_fathers_name_rus', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')])),
                ('attendee_contact_email', models.EmailField(blank=True, max_length=100)),
                ('attendee_contact_phone', models.CharField(blank=True, max_length=20)),
                ('attendee_contact_position', models.CharField(blank=True, max_length=50)),
                ('attendee_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course')),
            ],
        ),
    ]
