# Generated by Django 5.0.2 on 2024-05-02 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='attendee_contact_fathers_name_rus',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='attendee_contact_first_name_rus',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='attendee_contact_last_name_rus',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='attendee_contact_phone',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='attendee_contact_position',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='attendee_course_price',
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_contact_comments',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_contract_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_fathers_name_rus',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')]),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_first_name_eng',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^([A-Z][-,a-z. ]+[ ]*)+$')]),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_first_name_rus',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')]),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_last_name_eng',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^([A-Z][-,a-z. ]+[ ]*)+$')]),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_last_name_rus',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')]),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
