# Generated by Django 5.0.2 on 2024-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_course_course_date_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_date_end',
            field=models.DateField(),
        ),
    ]
