# Generated by Django 5.0.2 on 2024-03-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_course_course_date_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='city',
            new_name='attendee_city',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='company',
            new_name='attendee_company',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='course',
            new_name='attendee_course_id',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='email',
            new_name='attendee_email',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='fathers_name',
            new_name='attendee_fathers_name',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='first_name',
            new_name='attendee_first_name',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='last_name',
            new_name='attendee_last_name',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='phone',
            new_name='attendee_phone',
        ),
    ]
