# Generated by Django 5.0.2 on 2024-03-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_rename_city_attendee_attendee_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='attendee_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course'),
        ),
    ]
