# Generated by Django 5.0.2 on 2024-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_attendee_attendee_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='attendee_email',
            field=models.EmailField(max_length=100),
        ),
    ]
