# Generated by Django 5.0.2 on 2024-03-25 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_attendee_attendee_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='attendee_fathers_name',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='attendee_first_name',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='attendee_last_name',
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_fathers_name_eng',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^([A-Z][-,a-z. ]+[ ]*)+$')]),
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_fathers_name_rus',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')]),
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_first_name_eng',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^([A-Z][-,a-z. ]+[ ]*)+$')]),
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_first_name_rus',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')]),
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_last_name_eng',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^([A-Z][-,a-z. ]+[ ]*)+$')]),
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_last_name_rus',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')]),
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendee_position',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendee_gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='Male', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_tutor',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^([А-Я][а-я-,. ]+[ ]*)+$')]),
        ),
    ]
