# Generated by Django 5.0.2 on 2024-03-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_remove_attendee_attendee_fathers_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('confirmed', 'Запланирован'), ('held', 'Проведен'), ('cancelled', 'Отменен')], default='planned', verbose_name='Статус'),
        ),
    ]
