# Generated by Django 5.0.2 on 2024-03-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_course_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='attendee_gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('confirmed', 'Подтвержден'), ('held', 'Проведен'), ('cancelled', 'Отменен')], default='planned', verbose_name='Статус'),
        ),
    ]
