# Generated by Django 5.0.2 on 2024-03-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_alter_attendee_attendee_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('Запланирован', 'Запланирован'), ('Подтвержден', 'Подтвержден'), ('Проведен', 'Проведен'), ('Отменен', 'Отменен')], default='planned', verbose_name='Статус'),
        ),
    ]
